#include<stdio.h>
#include<conio.h>
int sum(int a,int b);
void printstar(int n);
	{
		for(int i=0;i<n; i++);
		{
		printf("%c",'x');
		}
	    }

	    int takenumber()
	    {
	      int i;
	      printf("Enter a number");
	      scanf("%d",&i);
	      getch(i);
	    }
	    int main()
	    {
		int a,b,c;
		a=9;
		b=87;
		//c=sum(a,b);
		//printstar(7);
		//c=takennumber();
		//printf("The sum is %d",c);
		printf("Ther number entered is %d\n",c);
		getch();
		}
		int sum(int a,inbb)
		{
			getch();
		}



